# Generated by Django 3.1.2 on 2020-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_length', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueHistory',
            fields=[
                ('queue_hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_id', models.IntegerField()),
                ('queue_size', models.IntegerField()),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
