# Generated by Django 3.1.2 on 2020-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_length', '0002_queuehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuehistory',
            name='length_diff',
            field=models.IntegerField(default=0),
        ),
    ]
